config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #building a new route to list the tasks
  get '/tasks', to: 'tasks#index'

  get '/tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks',     to: 'tasks#create', as: :create_task

  get '/tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: "tasks#edit", as: :edit_task
  patch "tasks/:id",    to: "tasks#update", as: :update_task

  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task



end


# Rails.application.routes.draw do
#   get    "restaurants",          to: "restaurants#index"

#   get    "restaurants/new",      to: "restaurants#new"
#   post   "restaurants",          to: "restaurants#create"

#   # NB: The `show` route needs to be *after* `new` route.
#   get    "restaurants/:id",      to: "restaurants#show"

#   get    "restaurants/:id/edit", to: "restaurants#edit"
#   patch  "restaurants/:id",      to: "restaurants#update"

#   delete "restaurants/:id",      to: "restaurants#destroy"
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(title: params[:title],
                    description: params[:description],
                    completed: params[:completed])
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>


<%= link_to "Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<p></p>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
<p></p>

<%= link_to "Back to list", tasks_path %>